// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/fahani/asia-car/src/application/vehicle/command/in-fleet-vehicle"
	"github.com/fahani/asia-car/src/infrastructure/vehicle/write-model/repository/read-write"
)

// Injectors from wire.go:

func InitializeInFleetCommandHandler() *in_fleet_vehicle_command.InFleetVehicleCommandHandler {
	inMemoryVehicleRepository := in_memory_vehicle_read_write_repository.NewInMemoryVehicleRepository()
	inFleetVehicleCommandHandler := in_fleet_vehicle_command.NewInFleetVehicleCommandHandler(inMemoryVehicleRepository)
	return inFleetVehicleCommandHandler
}
