openapi: 3.0.0

info:
  description: 'Asia Car API'
  version: '1.0.0'
  title: 'Asia Car API'

servers:
  - url: 'http://localhost:9000'
    description: 'Development Asia Car API'

tags:
  - name: 'Vehicles'
    description: 'Everything about Vehicles'
  - name: 'Status'
    description: 'Everything about Status'


paths:
  /status:
    $ref: 'resources/status.yaml/#/paths/detail'

  /vehicles/in-fleet:
    $ref: 'resources/vehicle.yaml/#/paths/in-fleet'

  /vehicles/install:
    $ref: 'resources/vehicle.yaml/#/paths/install'

  /vehicles/update-battery:
    $ref: 'resources/vehicle.yaml/#/paths/update-battery'

  /vehicles/update-fuel:
    $ref: 'resources/vehicle.yaml/#/paths/update-fuel'

  /vehicles/update-mileage:
    $ref: 'resources/vehicle.yaml/#/paths/update-mileage'

  /vehicles/details:
    $ref: 'resources/vehicle.yaml/#/paths/details'



components:

  responses:
    Error400:
      description: 'Invalid argument'
      content:
        application/json:
          schema:
            properties:
              data:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: object
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: integer
                        description: 'The error code'
                        example: 400
                      message:
                        type: string
                        description: 'The error message'
                        example: 'Your JSON request is bad formed'

    Error401:
      description: 'Unauthorized'
      content:
        application/json:
          schema:
            properties:
              data:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: object
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: integer
                        description: 'The error code'
                        example: 401
                      message:
                        type: string
                        description: 'The error message'
                        example: 'The JSON you have provided in your request does not comply with the schema'

    Error404:
      description: 'Not found'
      content:
        application/json:
          schema:
            properties:
              data:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: object
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: integer
                        description: 'The error code'
                        example: 404
                      message:
                        type: string
                        description: 'The error message'
                        example: 'The resource cannot be found'

    Error500:
      description: 'General error'
      content:
        application/json:
          schema:
            properties:
              data:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: object
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: integer
                        description: 'The error code'
                        example: 500
                      message:
                        type: string
                        description: 'The error message'
                        example: 'General error'
